import Head from 'next/head';
// import { useWalletSelector } from '../hooks/wallet-selector';

import ContractView from '../components/ContractView';
import ExplainText from '../components/ExplainText';

type Props = {
  contractName: string;
}
export default function Home({ contractName }: Props) {
  // const { accountId, modal, signOut } = useWalletSelector(contractName);
  return (
    <>
      <Head>
        <title>React Boilerplate Template</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="relative flex min-h-screen flex-col justify-center overflow-hidden bg-gray-50 py-6 sm:py-12">
          <div className="absolute inset-0 [mask-image:linear-gradient(180deg,white,rgba(255,255,255,0))]"></div>
          <ContractView contractName={contractName} />
          <ExplainText />
        </div>
      </main>

    </>
  );
}

Home.getInitialProps = async () => {
  const contractName = process.env.CONTRACT_NAME || 'guest-book.testnet';
  return { contractName };
};
